version: '3'

services:
  # Laravel App
  app:
    container_name: laravel-docker
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80" 
    depends_on:
      - db
    networks:
      - internal

  # MySQL
  db:
    image: mysql:latest
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: test
      MYSQL_PASSWORD: test1234
    networks:
      - internal

networks:
  internal:
    driver: bridge